#!/bin/sh

[ "x$DEVTYPE" = "xusb_device" ] || exit 0

NAME="${ID_VENDOR_ID}_${ID_MODEL_ID}"
DESC="${NAME} ${ID_SERIAL}"
XS_KEY="qubes-usb-devices/$NAME"

xenstore-write "$XS_KEY/desc" "$DESC"

/sbin/modprobe xen-usbback 2> /dev/null || /sbin/modprobe usbbk
