#!/bin/sh

tmpf=`mktemp`

sudo xenstore-ls -f qubes-usb-devices | sort > $tmpf

cat << 'END' | diff -u - $tmpf
qubes-usb-devices/002 = ""
qubes-usb-devices/002/002 = ""
qubes-usb-devices/002/002/desc = "046a:0021 046a_0021"
qubes-usb-devices/002/003 = ""
qubes-usb-devices/002/003/desc = "045e:0745 Microsoft_Microsoft\xc2\xae_Nano_Transceiver_v1.0"
END

rm $tmpf
