#!/bin/sh

tmpf=`mktemp`

sudo xenstore-ls -f qubes-usb-devices | sort > $tmpf

cat << 'END' | diff -u - $tmpf
qubes-usb-devices/045e_0745 = ""
qubes-usb-devices/045e_0745/desc = "045e_0745 Microsoft_Microsoft\xc2\xae_Nano_Transceiver_v1.0"
qubes-usb-devices/046a_0021 = ""
qubes-usb-devices/046a_0021/desc = "046a_0021 046a_0021"
qubes-usb-devices/0781_5530 = ""
qubes-usb-devices/0781_5530/desc = "0781_5530 SanDisk_Cruzer_1942531DB09038A6"
qubes-usb-devices/07d1_3c0a = ""
qubes-usb-devices/07d1_3c0a/desc = "07d1_3c0a Ralink_11n_Adapter_1.0"
END

rm $tmpf
