#!/bin/sh

: "${PYTHON:=python}"
: "${TESTPYTHONPATH:=test-packages}"

PYTHONPATH="${TESTPYTHONPATH}:${PYTHONPATH}"
export PYTHONPATH

"${PYTHON}" setup.py egg_info --egg-base "${TESTPYTHONPATH}"
"${PYTHON}" -m qubes.tests.run "$@"
