#!/bin/sh
#
# chkconfig: 345 92 92
# description: Starts Qubes Network monitor
#
# Source function library.
. /etc/rc.d/init.d/functions

PIDFILE=/var/run/qubes/qubes_netwatcher.pid

start()
{
    type=$(/usr/bin/xenstore-read qubes_vm_type)
    start_netwatcher=$(/usr/bin/xenstore-read qubes-service/qubes-netwatcher)
    if [ -z "$start_netwatcher" ] && [ "$type" == "ProxyVM" ] || [ "$start_netwatcher" == "1" ]; then
        echo -n $"Starting Qubes Network monitor:"
        /sbin/ethtool -K eth0 sg off
        /usr/sbin/qubes_netwatcher &
        success
        echo ""
    fi
	return 0
}

stop()
{
    if [ -r "$PIDFILE" ]; then
        echo -n "Stopping Qubes Network monitor:"
        kill -9 $(cat $PIDFILE) 2>/dev/null  && success || failure
        echo ""
    fi
	return 0
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  *)
	echo $"Usage: $0 {start|stop}"
	exit 3
	;;
esac

exit $RETVAL
