"""mock libvirt module

WARNING: you did not import real libvirt module

This is needed, because we don't currently ship libvirt-python for templates.
The module contains libvirtError and openReadOnly() function, which
does nothing and raises the aforementioned exception. More functions can be
added as needed.
"""

class libvirtError(Exception):
    def get_error_code(self):
        return VIR_ERR_NO_DOMAIN

class virConnect:
    pass

class virDomain:
    pass

def openReadOnly(*args, **kwargs):
    raise libvirtError('mock module, always raises')

def registerErrorHandler(f, ctx):
    pass

VIR_DOMAIN_START_PAUSED = 1
VIR_DOMAIN_BLOCKED = 2
VIR_DOMAIN_RUNNING = 1
VIR_DOMAIN_PAUSED = 3
VIR_DOMAIN_SHUTDOWN = 4
VIR_DOMAIN_SHUTOFF = 5
VIR_DOMAIN_CRASHED = 6
VIR_DOMAIN_PMSUSPENDED = 7

VIR_ERR_NO_DOMAIN = 0

# Begin virDomainEventType
VIR_DOMAIN_EVENT_CRASHED = 8
VIR_DOMAIN_EVENT_CRASHED_CRASHLOADED = 1
VIR_DOMAIN_EVENT_CRASHED_PANICKED = 0

VIR_DOMAIN_EVENT_DEFINED = 0
VIR_DOMAIN_EVENT_DEFINED_ADDED = 0
VIR_DOMAIN_EVENT_DEFINED_FROM_SNAPSHOT = 3
VIR_DOMAIN_EVENT_DEFINED_RENAMED = 2
VIR_DOMAIN_EVENT_DEFINED_UPDATED = 1

VIR_DOMAIN_EVENT_PMSUSPENDED = 7
VIR_DOMAIN_EVENT_PMSUSPENDED_DISK = 1
VIR_DOMAIN_EVENT_PMSUSPENDED_MEMORY = 0

VIR_DOMAIN_EVENT_RESUMED = 4
VIR_DOMAIN_EVENT_RESUMED_FROM_SNAPSHOT = 2
VIR_DOMAIN_EVENT_RESUMED_MIGRATED = 1
VIR_DOMAIN_EVENT_RESUMED_POSTCOPY = 3
VIR_DOMAIN_EVENT_RESUMED_POSTCOPY_FAILED = 4
VIR_DOMAIN_EVENT_RESUMED_UNPAUSED = 0

VIR_DOMAIN_EVENT_SHUTDOWN = 6
VIR_DOMAIN_EVENT_SHUTDOWN_FINISHED = 0
VIR_DOMAIN_EVENT_SHUTDOWN_GUEST = 1
VIR_DOMAIN_EVENT_SHUTDOWN_HOST = 2

VIR_DOMAIN_EVENT_STARTED = 2
VIR_DOMAIN_EVENT_STARTED_BOOTED = 0
VIR_DOMAIN_EVENT_STARTED_FROM_SNAPSHOT = 3
VIR_DOMAIN_EVENT_STARTED_MIGRATED = 1
VIR_DOMAIN_EVENT_STARTED_RESTORED = 2
VIR_DOMAIN_EVENT_STARTED_WAKEUP = 4

VIR_DOMAIN_EVENT_STOPPED = 5
VIR_DOMAIN_EVENT_STOPPED_CRASHED = 2
VIR_DOMAIN_EVENT_STOPPED_DESTROYED = 1
VIR_DOMAIN_EVENT_STOPPED_FAILED = 5
VIR_DOMAIN_EVENT_STOPPED_FROM_SNAPSHOT = 6
VIR_DOMAIN_EVENT_STOPPED_MIGRATED = 3
VIR_DOMAIN_EVENT_STOPPED_SAVED = 4
VIR_DOMAIN_EVENT_STOPPED_SHUTDOWN = 0

VIR_DOMAIN_EVENT_SUSPENDED = 3
VIR_DOMAIN_EVENT_SUSPENDED_API_ERROR = 6
VIR_DOMAIN_EVENT_SUSPENDED_FROM_SNAPSHOT = 5
VIR_DOMAIN_EVENT_SUSPENDED_IOERROR = 2
VIR_DOMAIN_EVENT_SUSPENDED_MIGRATED = 1
VIR_DOMAIN_EVENT_SUSPENDED_PAUSED = 0
VIR_DOMAIN_EVENT_SUSPENDED_POSTCOPY = 7
VIR_DOMAIN_EVENT_SUSPENDED_POSTCOPY_FAILED = 8
VIR_DOMAIN_EVENT_SUSPENDED_RESTORED = 4
VIR_DOMAIN_EVENT_SUSPENDED_WATCHDOG = 3

VIR_DOMAIN_EVENT_TRAY_CHANGE_CLOSE = 1
VIR_DOMAIN_EVENT_TRAY_CHANGE_OPEN = 0

VIR_DOMAIN_EVENT_UNDEFINED = 1
VIR_DOMAIN_EVENT_UNDEFINED_REMOVED = 0
VIR_DOMAIN_EVENT_UNDEFINED_RENAMED = 1
# End virDomainEventType
