#!/bin/sh

NM_CONFIG_DIR=/etc/NetworkManager/system-connections
if [ -d $NM_CONFIG_DIR -a ! -h $NM_CONFIG_DIR ]; then
    mkdir -p /rw/config/NM-system-connections
    mv $NM_CONFIG_DIR/* /rw/config/NM-system-connections/ 2> /dev/null || true
    rmdir $NM_CONFIG_DIR
    ln -s /rw/config/NM-system-connections $NM_CONFIG_DIR
fi

exit 0
