#!/usr/bin/python

from qubesadmin import Qubes

def main():
    app = Qubes()
    for vm in app.domains:
        if vm.klass == 'DispVM' and not vm.is_running():
            if vm.auto_cleanup:
                del app.domains[vm]

main()
