all:
	true

install:
	mkdir -p $(DESTDIR)/usr/lib/qubes
	cp cleanup-dispvms $(DESTDIR)/usr/lib/qubes
	cp startup-misc.sh $(DESTDIR)/usr/lib/qubes
	cp fix-dir-perms.sh $(DESTDIR)/usr/lib/qubes/
	cp hypervisor.sh $(DESTDIR)/usr/lib/qubes/
