all:
	true

install:
	mkdir -p $(DESTDIR)/usr/lib/qubes
	cp unbind-pci-device.sh $(DESTDIR)/usr/lib/qubes
	cp cleanup-dispvms $(DESTDIR)/usr/lib/qubes
	cp startup-misc.sh $(DESTDIR)/usr/lib/qubes
	cp prepare-volatile-img.sh $(DESTDIR)/usr/lib/qubes
	cp vusb-ctl.py $(DESTDIR)/usr/lib/qubes/
	cp xl-qvm-usb-attach.py $(DESTDIR)/usr/lib/qubes/
	cp xl-qvm-usb-detach.py $(DESTDIR)/usr/lib/qubes/
	cp block-cleaner-daemon.py $(DESTDIR)/usr/lib/qubes/
	cp fix-dir-perms.sh $(DESTDIR)/usr/lib/qubes/
