#!/usr/bin/python2.6
#
# The Qubes OS Project, http://www.qubes-os.org
#
# Copyright (C) 2011  Marek Marczykowski <marmarek@mimuw.edu.pl>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
#

from qubes.qubes import QubesVmCollection, qubes_kernels_base_dir
from optparse import OptionParser;
import os

def main():
    usage = "usage: %prog <kernel>"
    parser = OptionParser (usage)
    (options, args) = parser.parse_args ()
    if (len (args) != 1):
        parser.error ("Missing argument!")
    kernel = args[0]
    
    if not os.path.exists(qubes_kernels_base_dir + "/" + kernel):
        print "Kernel {0} not installed".format(kernel)
        exit(1)   

    qvm_collection = QubesVmCollection()
    qvm_collection.lock_db_for_writing()
    qvm_collection.load()
    
    qvm_collection.set_default_kernel(kernel)

    qvm_collection.save()
    qvm_collection.unlock_db()

main()
