#!/bin/sh
#
# chkconfig: 345 92 92
# description: Starts Qubes Network monitor
#
# Source function library.
. /etc/rc.d/init.d/functions

PIDFILE=/var/run/qubes/qubes_netwatcher.pid

start()
{
	echo -n $"Starting Qubes Network monitor:"
	/sbin/ethtool -K eth0 sg off
	/usr/bin/qubes_netwatcher &
	success
	echo ""
	return 0
}

stop()
{
	echo -n "Stopping Qubes Network monitor:"
	kill -9 $(cat $PIDFILE) 2>/dev/null  && success || failure
	echo ""
	return 0
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  *)
	echo $"Usage: $0 {start|stop}"
	exit 3
	;;
esac

exit $RETVAL
