#!/bin/sh
#
# chkconfig: 345 90 90
# description: Executes Qubes core scripts at VM boot
#
# Source function library.
. /etc/rc.d/init.d/functions

start()
{
	echo -n $"Executing Qubes Core scripts:"

	if ! [ -x /usr/bin/xenstore-read ] ; then
		echo "ERROR: /usr/bin/xenstore-read not found!"
		exit 1
	fi

	modprobe evtchn

	# Set permissions to /proc/xen/xenbus, so normal user can use xenstore-read
	chmod 666 /proc/xen/xenbus

	name=$(/usr/bin/xenstore-read name)
	if ! [ -f /etc/this_is_dvm ] ; then
		# we don't want to set hostname for DispVM
		# because it makes some of the pre-created dotfiles invalid (e.g. .kde/cache-<hostname>)
		# (let's be frank: nobody's gonna use xterm on DispVM)
		hostname $name
	fi

	ip=$(/usr/bin/xenstore-read qubes_ip)
	netmask=$(/usr/bin/xenstore-read qubes_netmask)
	gateway=$(/usr/bin/xenstore-read qubes_gateway)
	secondary_dns=$(/usr/bin/xenstore-read qubes_secondary_dns)
	if [ x$ip != x ]; then
		/sbin/ifconfig eth0 $ip netmask 255.255.255.255 up
		/sbin/route add default dev eth0
		echo "nameserver $gateway" > /etc/resolv.conf
		echo "nameserver $secondary_dns" >> /etc/resolv.conf
	fi

	if [ -e /dev/xvdb ] ; then
		mount /rw

        if ! [ -d /rw/home ] ; then
            echo
            echo "--> Virgin boot of the VM: Linking /home to /rw/home"

            mkdir -p /rw/config
            touch /rw/config/rc.local

            mkdir -p /rw/home
            cp -a /home.orig/user /home

            mkdir -p /rw/usrlocal
            cp -a /usr/local.orig/* /usr/local

            touch /var/lib/qubes/first_boot_completed
        fi
	fi

	/usr/lib/qubes/qrexec_agent 2>/var/log/qubes/qrexec_agent.log &

	[ -x /rw/config/rc.local ] && /rw/config/rc.local

	if ! [ -f /home/user/.gnome2/nautilus-scripts/.scripts_created ] ; then
		echo "Creating symlinks for nautilus actions..."
		su user -c 'mkdir -p /home/user/.gnome2/nautilus-scripts'
		su user -c 'ln -s /usr/lib/qubes/qvm-copy-to-vm2.gnome /home/user/.gnome2/nautilus-scripts/"Copy to other AppVM"'
		su user -c 'ln -s /usr/bin/qvm-open-in-dvm2 /home/user/.gnome2/nautilus-scripts/"Open in DisposableVM"'
		su user -c 'touch /home/user/.gnome2/nautilus-scripts/.scripts_created'
	fi

	success
	echo ""

	type=$(/usr/bin/xenstore-read qubes_vm_type)
	if [ "$type" == "ProxyVM" ]; then
		/sbin/service ntpd start
	fi
	return 0
}

stop()
{
	return 0
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  *)
	echo $"Usage: $0 {start|stop}"
	exit 3
	;;
esac

exit $RETVAL
