#!/bin/sh
addrule()
{
        if [ $FIRSTONE = yes ] ; then
                FIRSTONE=no
                RULE1="-A PREROUTING -d $NS1 -p udp --dport 53 -j DNAT --to $1"
        else
                RULE2="-A PREROUTING -d $NS2 -p udp --dport 53 -j DNAT --to $1"
                NS=$NS2
        fi
}
export PATH=$PATH:/sbin:/bin
source /var/run/qubes/qubes_ns
if [ "X"$NS1 = "X" ] ; then exit ; fi
iptables -t nat -F PREROUTING
FIRSTONE=yes
grep ^nameserver /etc/resolv.conf | head -2 |
        (
        while read x y z ; do
                addrule "$y"
        done
        (echo "*nat"; echo $RULE1; echo $RULE2; echo COMMIT) | iptables-restore -n
        )

