#!/bin/sh

. "${PM_FUNCTIONS}"

sync_qubes_vms_wallclock()
{
/usr/bin/qvm-sync-dom0-clock
DATE=$(date)
echo
echo "Syncing VMs clock to: $DATE"
qvm-run --all --exclude=`qvm-get-clockvm` -u root "date -s \"$DATE\""
}

case "$1" in
        thaw|resume) sync_qubes_vms_wallclock ;;
        *) exit 0 ;;
esac
