#!/bin/sh

. "${PM_FUNCTIONS}"

pause_vms()
{
echo
qvm-run --all --pause
}


unpause_vms()
{
echo
qvm-run --all --unpause
}


case "$1" in
        thaw|resume) unpause_vms ;;
        suspend|hibernate) pause_vms ;;
        *) exit 0 ;;
esac
